# -*- coding: utf-8 -*-
#
# Cookbook Name:: elite
# Spec:: git
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require_relative 'spec_helper'

describe 'elite::git' do
  let(:subject) do
    ChefSpec::SoloRunner.new(step_into: %w(elite_git),
                             platform: 'debian',
                             version: '8.0') do |node|
      node.override['elite']['users'] = %w(sliim foo)
      node.override['elite']['groups'] = %w(elite)
      node.override['elite']['sliim']['name'] = 'Sliim'
      node.override['elite']['sliim']['email'] = 'sliim@mailoo.org'
      node.override['elite']['sliim']['home'] = '/home/sliim'
      node.override['elite']['sliim']['group'] = 'elite'
      node.override['elite']['sliim']['groups'] = %w(elite)
      node.override['elite']['sliim']['dotfd'] = '/home/sliim/.dotfiles'
      node.override['elite']['sliim']['git']['cookbook'] = 'elite'
    end.converge(described_recipe)
  end

  it 'includes recipe[elite::default]' do
    expect(subject).to include_recipe('elite::default')
  end

  it 'creates elite_git[sliim]' do
    expect(subject).to create_elite_git('sliim')
      .with(username: 'Sliim',
            email: 'sliim@mailoo.org',
            cookbook: 'elite')
  end

  it 'installs package[git]' do
    expect(subject).to install_package('git')
  end

  it 'creates template[/home/sliim/.dotfiles/gitconfig]' do
    config_file = '/home/sliim/.dotfiles/gitconfig'
    matches = [start_with('# Generated by Chef!'),
               /name = Sliim$/,
               /email = sliim@mailoo\.org$/,
               /signingkey = "Sliim <sliim@mailoo\.org>"$/]

    expect(subject).to create_template(config_file)
      .with(owner: 'sliim',
            group: 'elite',
            mode: '0640',
            source: 'gitconfig.erb',
            cookbook: 'elite')

    matches.each do |m|
      expect(subject).to render_file(config_file).with_content(m)
    end
  end

  it 'creates cookbook_file[/home/sliim/.dotfiles/gitignore]' do
    expect(subject).to create_cookbook_file('/home/sliim/.dotfiles/gitignore')
      .with(owner: 'sliim',
            group: 'elite',
            mode: '0640',
            source: 'gitignore',
            cookbook: 'elite')
  end

  it 'creates elite_dotlink[gitconfig]' do
    expect(subject).to create_elite_dotlink('gitconfig')
  end

  it 'creates elite_dotlink[gitignore]' do
    expect(subject).to create_elite_dotlink('gitignore')
  end
end
