# -*- coding: utf-8 -*-
#
# Cookbook Name:: elite
# Spec:: gtk
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require_relative 'spec_helper'

describe 'elite::gtk' do
  let(:subject) do
    ChefSpec::SoloRunner.new(step_into: %w(elite_gtk),
                             file_cache_path: '/var/chef/cache',
                             platform: 'debian',
                             version: '8.0') do |node|
      node.override['elite']['users'] = %w(sliim foo)
      node.override['elite']['groups'] = %w(elite)
      node.override['elite']['sliim']['email'] = 'sliim@mailoo.org'
      node.override['elite']['sliim']['home'] = '/home/sliim'
      node.override['elite']['sliim']['group'] = 'elite'
      node.override['elite']['sliim']['groups'] = %w(elite)
      node.override['elite']['sliim']['dotfd'] = '/home/sliim/.dotfiles'
      node.override['elite']['sliim']['gtk']['font_name'] = 'font-name'
      node.override['elite']['sliim']['gtk']['theme_name'] = 'Cyanized'
      node.override['elite']['sliim']['gtk']['theme_rc'] = 'gtkrc.erb'
      node.override['elite']['sliim']['gtk']['icon_theme_name'] = 'icon-theme-name'
      node.override['elite']['sliim']['gtk']['toolbar_style'] = 'TOOLBAR'
      node.override['elite']['sliim']['gtk']['toolbar_icon_size'] = '42'
      node.override['elite']['sliim']['gtk']['color'] = {
        'bg_color' => 'bg-color',
        'selected_bg_color' => 'selected-bg-color',
        'base_color' => 'base-color',
        'fg_color' => 'fg-color',
        'selected_fg_color' => 'selected-fg-color',
        'text_color' => 'text-,color',
        'tooltip_bg_color' => 'tooltip-bg-color',
        'tooltip_fg_color' => 'tooltip-fg-color',
        'link_color' => 'link-color',
        'panel_bg' => 'panel-bg',
      }
    end.converge(described_recipe)
  end

  it 'includes recipe[elite::default]' do
    expect(subject).to include_recipe('elite::default')
  end

  it 'includes recipe[elite::dotfiles]' do
    expect(subject).to include_recipe('elite::dotfiles')
  end

  it 'creates elite_gtk[sliim]' do
    expect(subject).to create_elite_gtk('sliim')
      .with(cookbook: 'elite')
  end

  ['libgtk2.0-0', 'libgtk2.0-dev', 'gtk2-engines',
   'gtk2-engines-pixbuf', 'gtk2-engines-murrine',
   'python-gconf'].each do |pkg|
    it "installs package[gt#{pkg}]" do
      expect(subject).to install_package(pkg)
    end
  end

  it 'creates template[/home/sliim/.dotfiles/gtkrc-2.0]' do
    config_file = '/home/sliim/.dotfiles/gtkrc-2.0'
    matches = [start_with('# Generated by Chef!'),
               /^gtk-font-name = "font-name"$/,
               /^gtk-theme-name = "Cyanized"$/,
               /^gtk-icon-theme-name = "icon-theme-name"$/,
               /^gtk-toolbar-style = TOOLBAR$/,
               /^gtk-toolbar-icon-size = 42$/]

    expect(subject).to create_template(config_file)
      .with(owner: 'sliim',
            group: 'elite',
            mode: '0640',
            source: 'gtkrc-2.0.erb')

    matches.each do |m|
      expect(subject).to render_file(config_file).with_content(m)
    end
  end

  it 'creates directory[/home/sliim/.dotfiles/themes]' do
    expect(subject).to create_directory('/home/sliim/.dotfiles/themes')
      .with(owner: 'sliim',
            group: 'elite',
            mode: '0750')
  end

  it 'creates remote_directory[/home/sliim/.dotfiles/themes/Cyanized]' do
    expect(subject).to create_remote_directory('/home/sliim/.dotfiles/themes/Cyanized')
      .with(owner: 'sliim',
            group: 'elite',
            mode: '0750',
            files_owner: 'sliim',
            files_group: 'elite',
            files_mode: '0640',
            source: 'gtk/themes/Cyanized')
  end

  it 'creates template[/home/sliim/.dotfiles/themes/Cyanized/gtk-2.0/gtkrc]' do
    config_file = '/home/sliim/.dotfiles/themes/Cyanized/gtk-2.0/gtkrc'
    matches = [start_with('# Generated by Chef!'),
               /fg_color:fg-color/,
               /selected_fg_color:selected-fg-color/]

    expect(subject).to create_template(config_file)
      .with(owner: 'sliim',
            group: 'elite',
            mode: '0640',
            source: 'gtk/themes/Cyanized/gtkrc.erb')

    matches.each do |m|
      expect(subject).to render_file(config_file).with_content(m)
    end
  end

  it 'creates directory[/home/sliim/.dotfiles/icons]' do
    expect(subject).to create_directory('/home/sliim/.dotfiles/icons')
      .with(owner: 'sliim',
            group: 'elite',
            mode: '0750')
  end

  it 'creates cookbook_file[/var/chef/cache/icons.tar.gz]' do
    expect(subject).to create_cookbook_file('/var/chef/cache/icons.tar.gz')
      .with(source: 'gtk/icons/icon-theme-name.tar.gz')
  end

  it 'runs execute[tar --keep-newer-files -xzf /var/chef/cache/icons.tar.gz]' do
    expect(subject).to run_execute('tar --keep-newer-files -xzf /var/chef/cache/icons.tar.gz')
      .with(cwd: '/home/sliim/.dotfiles/icons',
            user: 'sliim',
            group: 'elite')
  end

  ['gtkrc-2.0', 'theme', 'icons'].each do |f|
    it "creates elite_dotlink[sliim-#{f}]" do
      expect(subject).to create_elite_dotlink("sliim-#{f}")
        .with(owner: 'sliim',
              file: f)
    end
  end
end
