# -*- coding: utf-8 -*-
#
# Cookbook Name:: elite
# Spec:: moc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require_relative 'spec_helper'

describe 'elite::moc' do
  let(:subject) do
    ChefSpec::SoloRunner.new(step_into: %w(elite_moc elite_dotlink),
                             platform: 'debian',
                             version: '9.0') do |node|
      node.override['elite']['users'] = %w(sliim foo)
      node.override['elite']['groups'] = %w(elite)
      node.override['elite']['sliim']['home'] = '/home/sliim'
      node.override['elite']['sliim']['group'] = 'elite'
      node.override['elite']['sliim']['groups'] = %w(elite)
      node.override['elite']['sliim']['dotfd'] = '/home/sliim/.dotfiles'
      node.override['elite']['sliim']['moc']['config'] = {
        'Theme' => 'yellow_red_theme',
        'MusicDir' => '~/Music',
      }
    end.converge(described_recipe)
  end

  it 'includes recipe[elite::default]' do
    expect(subject).to include_recipe('elite::default')
  end

  it 'includes recipe[elite::dotfiles]' do
    expect(subject).to include_recipe('elite::dotfiles')
  end

  it 'creates elite_moc[sliim]' do
    expect(subject).to create_elite_moc('sliim')
  end

  it 'does not create elite_moc[foo]' do
    expect(subject).to_not create_elite_moc('foo')
  end

  it 'create directory[/home/sliim/.dotfiles/moc]' do
    expect(subject).to create_directory('/home/sliim/.dotfiles/moc')
      .with(owner: 'sliim',
            group: 'elite',
            mode: '0750')
  end

  it 'creates elite_dotlink[sliim-moc]' do
    expect(subject).to create_elite_dotlink('sliim-moc')
      .with(owner: 'sliim',
            file: 'moc')
  end

  it 'creates link[/home/sliim/.moc]' do
    expect(subject).to create_link('/home/sliim/.moc')
      .with(owner: 'sliim',
            group: 'elite',
            link_type: :symbolic,
            to: '/home/sliim/.dotfiles/moc')
  end

  it 'installs package[moc]' do
    expect(subject).to install_package('moc')
  end

  it 'creates template[/home/sliim/.dotfiles/moc/config]' do
    config_file = '/home/sliim/.dotfiles/moc/config'
    matches = [start_with('# Generated by Chef!'),
               /^Theme = yellow_red_theme$/,
               %r{^MusicDir = ~/Music$}]

    expect(subject).to create_template(config_file)
      .with(owner: 'sliim',
            group: 'elite',
            mode: '0640',
            source: 'ini.erb',
            cookbook: 'elite')

    matches.each do |m|
      expect(subject).to render_file(config_file).with_content(m)
    end
  end
end
