# -*- coding: utf-8 -*-
#
# Cookbook Name:: elite
# Spec:: stumpwm
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require_relative 'spec_helper'

describe 'elite::stumpwm' do
  let(:subject) do
    ChefSpec::SoloRunner.new(step_into: %w(elite_stumpwm),
                             platform: 'debian',
                             version: '8.0') do |node|
      node.override['elite']['users'] = %w(sliim foo)
      node.override['elite']['groups'] = %w(elite)
      node.override['elite']['sliim']['email'] = 'sliim@mailoo.org'
      node.override['elite']['sliim']['home'] = '/home/sliim'
      node.override['elite']['sliim']['group'] = 'elite'
      node.override['elite']['sliim']['groups'] = %w(elite)
      node.override['elite']['sliim']['dotfd'] = '/home/sliim/.dotfiles'
      node.override['elite']['sliim']['stumpwm']['wallpaper'] = 'wallpaper-01.jpg'
      node.override['elite']['sliim']['stumpwm']['prefix_key'] = 's-f'
      node.override['elite']['sliim']['stumpwm']['pre_commands'] = ['run-something']
      node.override['elite']['sliim']['stumpwm']['post_commands'] = ['run-another-thing']
      node.override['elite']['sliim']['stumpwm']['color']['fg'] = 'Black'
      node.override['elite']['sliim']['stumpwm']['color']['bg'] = 'White'
      node.override['elite']['sliim']['stumpwm']['color']['focus'] = 'Black'
      node.override['elite']['sliim']['stumpwm']['color']['border'] = 'grey15'
      node.override['elite']['sliim']['stumpwm']['color']['float_focus'] = 'White'
      node.override['elite']['sliim']['stumpwm']['color']['float_unfocus'] = 'Black'
      node.override['elite']['sliim']['stumpwm']['color']['grab_pointer_fg'] = 'White'
      node.override['elite']['sliim']['stumpwm']['color']['grab_pointer_bg'] = 'Black'
    end.converge(described_recipe)
  end

  it 'includes recipe[elite::default]' do
    expect(subject).to include_recipe('elite::default')
  end

  it 'includes recipe[elite::dotfiles]' do
    expect(subject).to include_recipe('elite::dotfiles')
  end

  it 'creates elite_stumpwm[sliim]' do
    expect(subject).to create_elite_stumpwm('sliim')
      .with(cookbook: 'elite')
  end

  it 'installs package[stumpwm]' do
    expect(subject).to install_package('stumpwm')
  end

  it 'creates template[/home/sliim/.dotfiles/stumpwmrc]' do
    config_file = '/home/sliim/.dotfiles/stumpwmrc'
    matches = [start_with(';; Generated by Chef!'),
               /^\(set-prefix-key \(kbd "s-f"\)\)$/,
               /run-shell-command "run-something"/,
               %r{run-shell-command "feh --bg-scale ~/pics/wallpaper-01.jpg"},
               /run-shell-command "run-another-thing"/,
               /\*startup-message\* "Welcome Sliim!"$/,
               /screen-fg-color "Black"\)$/,
               /screen-bg-color "White"\)$/,
               /screen-focus-color "Black"\)$/,
               /screen-border-color "grey15"\)$/,
               /screen-float-focus-color "White"\)$/,
               /screen-float-unfocus-color "Black"\)$/,
               /grab-pointer-foreground\* \(lookup-color \(current-screen\) "White"\)/,
               /grab-pointer-background\* \(lookup-color \(current-screen\) "Black"\)/]

    expect(subject).to create_template(config_file)
      .with(owner: 'sliim',
            group: 'elite',
            mode: '0640',
            source: 'stumpwmrc.erb')

    matches.each do |m|
      expect(subject).to render_file(config_file).with_content(m)
    end
  end

  it 'creates remote_directory[/home/sliim/.dotfiles/stumpwm.d]' do
    expect(subject).to create_remote_directory('/home/sliim/.dotfiles/stumpwm.d')
      .with(owner: 'sliim',
            group: 'elite',
            mode: '0750',
            files_owner: 'sliim',
            files_group: 'elite',
            files_mode: '0640',
            source: 'stumpwm.d')
  end

  it 'creates elite_dotlink[sliim-stumpwmrc]' do
    expect(subject).to create_elite_dotlink('sliim-stumpwmrc')
      .with(owner: 'sliim',
            file: 'stumpwmrc')
  end

  it 'creates elite_dotlink[sliim-stumpwm.d]' do
    expect(subject).to create_elite_dotlink('sliim-stumpwm.d')
      .with(owner: 'sliim',
            file: 'stumpwm.d')
  end

  it 'creates elite_bin[sliim-stumpish]' do
    expect(subject).to create_elite_bin('sliim-stumpish')
      .with(owner: 'sliim',
            script: 'stumpish',
            cookbook: 'elite',
            source_dir: 'bin/')
  end

  it 'creates elite_bin[sliim-stumpwm]' do
    expect(subject).to create_elite_bin('sliim-stumpwm')
      .with(owner: 'sliim',
            script: 'stumpwm',
            cookbook: 'elite',
            source_dir: 'bin/')
  end

  it 'creates elite_picture[sliim-wallpaper-01.jpg]' do
    expect(subject).to create_elite_picture('sliim-wallpaper-01.jpg')
      .with(owner: 'sliim',
            pic: 'wallpaper-01.jpg',
            cookbook: 'elite',
            source_dir: 'pics/')
  end
end
